### ISSUE TITLE
1-518-BLK-TIME disconnected

### ISSUE THREAD

**Issue by fjccoin** [MuleTools/MuleTools#10]
Vocal message with latest block hash (1-518-BLK-TIME): +1(518)255-8463  has been disconnected. How can we reconnect it? Whats required? Thanks

**Comment by SamouraiDev** [comment]
The service is provided by Blockstream.

**Comment by fjccoin** [comment]
Thanks. I'll look into it more and report back.

**Comment by fjccoin** [comment]
"It was setup for fun. We can put it up again maybe :)"
https://twitter.com/fjccoin/status/1053073355849502723
